### ISSUE TITLE
Multiplayer doesn't work

### ISSUE THREAD

**Issue by pizzadude** [flathub/net.cubers.assault.AssaultCube#1]
Multiplayer doesn't work ~~and there is no network permission in this flatpak~~

**Comment by pizzadude** [comment]
I already tried enabling networking via flatseal and it couldn't connect to the server, but the rpm did.

**Comment by Mailaender** [comment]
https://github.com/flathub/net.cubers.assault.AssaultCube/commit/32b2719143186101d60e4578261a0e55cfcd54ef

**Comment by pizzadude** [comment]
doesn't fix it

**Comment by ghost** [comment]
Still experiencing this issue months later.

**Comment by AsciiWolf** [comment]
I see this in log: 

```
own IP: 0.0.0.0, censored own IP: 0.0.0.0, --, clock offset -464343 hours -3 minutes
```

This may be the problem.

**Comment by AsciiWolf** [comment]
I have tried copying the game files (`/app/share/assaultcube`) to my home directory and running it directly. The network issue is still there. So, it does not seem to be caused by the Flatpak sandbox.

**Comment by AsciiWolf** [comment]
So, the problem seems to be in the `bin_unix/native_client` binary. Everything works correctly after replacing it with binary from the official _AssaultCube_v1.3.0.2_LockdownEdition_RC1.tar.bz2_ archive.

I am suspecting the bundled ENet library or maybe some missing configure/make switch.

**Comment by AsciiWolf** [comment]
It also may be caused by building against a much newer SDL version than the official binary did (2.24.0 vs 2.0.10).

**Comment by Mailaender** [comment]
Interesting. I thought this was some kind of syscall being blocked by Flatpak. It is however this flag which is even documented deep inside: [packaging_guide.txt](https://github.com/assaultcube/AC/blob/da5cb69c009b4c8fafbb2498787bd4b05d0274e7/source/dev_tools/packaging_guide.txt#L28)
